# Generated by Django 5.2.4 on 2025-08-09 09:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytasks1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, help_text="项目标题（可选）", max_length=200),
                ),
                ("content", models.TextField(blank=True, help_text="文本内容")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("photo", "Photo"),
                            ("message", "Message"),
                            ("emotion", "Emotion"),
                            ("days", "Days Matter"),
                        ],
                        help_text="项目分类",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="创建时间"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="最后更新时间")),
            ],
            options={
                "verbose_name": "Archive Item",
                "verbose_name_plural": "Archive Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="上传的媒体文件", upload_to="archive_media/%Y/%m/%d/"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("audio", "Audio")],
                        help_text="媒体类型（图片/音频）",
                        max_length=10,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="上传时间"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(blank=True, help_text="原始文件名", max_length=255),
                ),
                (
                    "archive_item",
                    models.ForeignKey(
                        help_text="关联的归档项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="mytasks1.archiveitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
            },
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
